# Generated by Django 2.1.8 on 2019-04-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
